name: Update Binary

on:
  workflow_dispatch:
  # schedule:
  # 5am UTC daily
  # - cron: "00 5 * * *"

jobs:
  update-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest Release
        working-directory: ./nowsecure/bin
        env:
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
        run: |
          LATEST_VERSION=$(gh release --repo nowsecure/nowsecure-ci view --json tagName --jq '.tagName')
          CURRENT_VERSION=$(cat version)

          if [ "$LATEST_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Current version ($CURRENT_VERSION) is latest"
          else
            echo $LATEST_VERSION > version

            gh release --repo nowsecure/nowsecureci download --clobber \
              --pattern 'ns_darwin-arm64' \
              --pattern 'ns_linux-amd64' \
              --patern 'ns_windows-amd64'

            echo "RELEASE_NOTES=$(gh release --repo nowsecure/nowsecure-ci view --json body --jq '.body') >> $GITHUB_ENV
          fi

          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Commit changes
        working-directory: ./nowsecure/bin
        run: |
          PR_TITLE="chore(deps): update nowsecure-ci binary to ${{ env.LATEST_VERSION }}"
          BRANCH_NAME="chore/ns-binary/${{ env.LATEST_VERSION }}"

          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "$PR_TITLE"
            git checkout -b $BRANCH_NAME
            git add .
            gh pr create --title "$PR_TITLE" --body "# NowSecure CI Release Notes \n ${{ env.RELEASE_NOTES }}"
          fi
