name: Lint

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
    branches: [ "main" ]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Versions
        run: |
          VSS_VERSION=$(jq -r '.version' vss-extension.json)
          TASK_VERSION=$(jq -j '[.version.Major, .version.Minor, .version.Patch] | join(".")' nowsecure/task.json)
          if [ "$VSS_VERSION" = "$TASK_VERSION" ]; then
            echo "Versions match $VSS_VERSION"
          else
            echo "Version from vss file ($VSS_VERSION) and task file ($TASK_VERSION) do not match"
            exit 1
          fi
  biome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./nowsecure
      - name: Biome Check
        run: npx @biomejs/biome@2 check nowsecure/index.ts
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.5.0
        with:
          files: .
          config_file: .markdownlint.yml
          dot: true
      - name: typos-action spellchecker
        uses: crate-ci/typos@v1.33.1
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
